apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: helm-chart-testing-main
      imagePullPolicy: Always
      imageRegistry: docker.io/helm-chart-testing
      imagePullSecretName: imagepull-docker
      credentialId: credential_f68ee5ec-c7d1-4266-b7a0-501a3ee0e570
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: helm-chart-testing
    version: v1.0.0
    applicationId: app_0546a175-bf96-4a0d-a08b-d1762565b4e9
    projectId: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_4754af0a-b249-4956-88c3-e47b84548047
    environmentName: staging
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: helm-chart-testing
  serviceType: ClusterIP
  version: v1.0.0
  namespace: env-testing-staging
