apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-project-dev-ingress
  namespace: env-testing-dev
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
    applicationId: app_0b9fa1cc-ab6f-475d-8b8c-b1f6534627dd
    environmentId: env_e5d8feaf-553c-4cd5-8f37-09e5b58df4be
spec:
  tls:
    - secretName: ingress
      hosts:
        - test.com
  rules:
    - host: test.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-project-v1-0-0
                port:
                  number: 80
