apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: qa-testing
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: qa-testing
    version: v1.0.0
    applicationId: app_2b49ea1d-5ca7-496e-be05-00308cc61008
    projectId: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_9622c628-6eeb-468b-b00b-a5db2d2694a4
    environmentName: production
  namespace: env-testing-production
