apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qa-testing-v1-0-0
  namespace: env-testing-staging
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
    environmentId: env_4754af0a-b249-4956-88c3-e47b84548047
    applicaitonId: app_2b49ea1d-5ca7-496e-be05-00308cc61008
spec:
  interval: 5m0s
  chart:
    spec:
      chart: Dockerfile
      sourceRef:
        kind: GitRepository
        name: qa-testing-v1-0-0
        namespace: env-testing-staging
      valuesFiles:
        - Dockerfile
  values: {}
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: qa-testing-v1-0-0
            patch: |
              - op: add
                path: /spec/template/metadata/labels/organizationId
                value: org_6de1b366-9da6-4d55-b363-f5a2c4382016
              - op: add
                path: /spec/template/metadata/labels/projectId
                value: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
              - op: add
                path: /spec/template/metadata/labels/applicationId
                value: app_2b49ea1d-5ca7-496e-be05-00308cc61008
              - op: add
                path: /spec/template/metadata/labels/environmentId
                value: env_4754af0a-b249-4956-88c3-e47b84548047
              - op: add
                path: /spec/template/metadata/labels/version
                value: v1.0.0
          - target: {}
            patch: |
              - op: add
                path: /metadata/labels/organizationId
                value: org_6de1b366-9da6-4d55-b363-f5a2c4382016
              - op: add
                path: /metadata/labels/projectId
                value: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
              - op: add
                path: /metadata/labels/applicationId
                value: app_2b49ea1d-5ca7-496e-be05-00308cc61008
              - op: add
                path: /metadata/labels/environmentId
                value: env_4754af0a-b249-4956-88c3-e47b84548047
              - op: add
                path: /metadata/labels/version
                value: v1.0.0
          - target:
              group: batch
              version: v1
              kind: Job
              name: qa-testing-v1-0-0
            patch: |
              - op: add
                path: /spec/template/metadata/labels/organizationId
                value: org_6de1b366-9da6-4d55-b363-f5a2c4382016
              - op: add
                path: /spec/template/metadata/labels/projectId
                value: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
              - op: add
                path: /spec/template/metadata/labels/applicationId
                value: app_2b49ea1d-5ca7-496e-be05-00308cc61008
              - op: add
                path: /spec/template/metadata/labels/environmentId
                value: env_4754af0a-b249-4956-88c3-e47b84548047
              - op: add
                path: /spec/template/metadata/labels/version
                value: v1.0.0
          - target:
              group: batch
              version: v1
              kind: CronJob
              name: qa-testing-v1-0-0
            patch: |
              - op: add
                path: /spec/jobTemplate/metadata/labels/organizationId
                value: org_6de1b366-9da6-4d55-b363-f5a2c4382016
              - op: add
                path: /spec/jobTemplate/metadata/labels/projectId
                value: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
              - op: add
                path: /spec/jobTemplate/metadata/labels/applicationId
                value: app_2b49ea1d-5ca7-496e-be05-00308cc61008
              - op: add
                path: /spec/jobTemplate/metadata/labels/environmentId
                value: env_4754af0a-b249-4956-88c3-e47b84548047
              - op: add
                path: /spec/jobTemplate/metadata/labels/version
                value: v1.0.0
          - target:
              group: batch
              version: v1
              kind: CronJob
              name: qa-testing-v1-0-0
            patch: |
              - op: add
                path: /spec/jobTemplate/spec/template/metadata/labels/organizationId
                value: org_6de1b366-9da6-4d55-b363-f5a2c4382016
              - op: add
                path: /spec/jobTemplate/spec/template/metadata/labels/projectId
                value: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
              - op: add
                path: /spec/jobTemplate/spec/template/metadata/labels/applicationId
                value: app_2b49ea1d-5ca7-496e-be05-00308cc61008
              - op: add
                path: /spec/jobTemplate/spec/template/metadata/labels/environmentId
                value: env_4754af0a-b249-4956-88c3-e47b84548047
              - op: add
                path: /spec/jobTemplate/spec/template/metadata/labels/version
                value: v1.0.0
          - target:
              group: apps
              version: v1
              kind: StatefulSet
              name: qa-testing-v1-0-0
            patch: |
              - op: add
                path: /spec/template/metadata/labels/organizationId
                value: org_6de1b366-9da6-4d55-b363-f5a2c4382016
              - op: add
                path: /spec/template/metadata/labels/projectId
                value: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
              - op: add
                path: /spec/template/metadata/labels/applicationId
                value: app_2b49ea1d-5ca7-496e-be05-00308cc61008
              - op: add
                path: /spec/template/metadata/labels/environmentId
                value: env_4754af0a-b249-4956-88c3-e47b84548047
              - op: add
                path: /spec/template/metadata/labels/version
                value: v1.0.0
