apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers: []
  name: qa-helm-testing-2
  type: HelmChart
  horizontalAutoScalingRules: []
  volumes: []
  version: v1.0.0
  labels:
    app: qa-helm-testing-2
    version: v1.0.0
    applicationId: app_79e507eb-5175-4252-9fb3-d7a80009740b
    projectId: project_6665615c-77bd-4dc5-9bb1-37ca0b0f19e6
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    environmentId: env_e5d8feaf-553c-4cd5-8f37-09e5b58df4be
    environmentName: development
  namespace: env-testing-dev
